name: Sync propositions from Google Sheet

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 * * * *"  # hourly

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Make tmp dir
        run: mkdir -p tmp

      - name: Download published CSV from Google Sheets
        run: |
          curl -L "https://docs.google.com/spreadsheets/d/e/2PACX-1vSerSSb4-K9RII_tmNfAO_4UqqWBA8yWh3bj2MMsMe9EGxBlH5QT-r0qNfkg1Z96KqgVTT1zX1mQwWq/pub?output=csv" -o tmp/propositions.csv

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Convert CSV → JSON
        run: python scripts/sheet_to_json.py

      - name: Commit & push if changed
        run: |
          if git diff --quiet; then
            echo "No changes."
          else
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add propositions.json
            git commit -m "chore: sync propositions from Google Sheet"
            git push
          fi
